#!/bin/bash
# numbrite liitimine
# versioon 1
#
echo -n "Sisesta suvaline täisarv: "
read numbrid
# alustame kohe ka väljastus
echo -n "Numbrite $numbrid summa on "
# kui numbrid on negatiivsed - muudame positiivseks
if [ $numbrid -lt 0 ]; then
   numbrid=$(($numbrid * -1))
fi
# arvutame summa
summa=0
while [ $numbrid -gt 0 ]
do
  arv=$(($numbrid % 10))
  numbrid=$(($numbrid / 10))
  summa=$(($summa + $arv))
done
# väljastame
echo $summa
